### ISSUE TITLE
Class 'diversen\conf' not found in gps.php on line 88

### ISSUE THREAD

**Issue by magnus-eriksson** [diversen/gps-from-exif#1]
Hi,

I was trying your library out, and it seems like a simple solution for getting gmap position from exif-data.

However, it seems like you are using another class in your code that's not included in the package on row 88:  `$width = conf::getModuleIni('gallery_image_size');`.

I think it would be better to have the sizes ($width and $height) as a third and fourth arguments instead.

Cheers!

**Comment by diversen** [comment]
Yes, you are right. I moved the class from a larger lib where the `conf` class is part of, and forgot about this dependency in the `gps-from-exif` class. I added the `width` and `height` params, and removed the `conf` class, so it should been fixed with the new release `1.0.6`.

**Comment by magnus-eriksson** [comment]
Cool! :) :+1:
